export const API = {
  COMMON: {
    PUBLIC_CATEGORY: "api/client/category/search",
  },
  ADMIN: {
    GET_ALL_ORDER: "/admin/orders",
    GET_ORDER_BY_ID: "/admin/orders/:id",
    GET_ALL_SHOPS: "/admin/shops",
    GET_SHOP_BY_ID: "/admin/shops/:id",
    GET_ALL_USERS: "/admin/users",
    GET_USER_BY_ID: "/admin/users/:id",
    GET_DASHBOARD_STATS: "/admin/stats",
    UPDATE_ORDER_STATUS: "/admin/orders/status/:id",
    GET_ALL_PENDING_SHOPS: "/admin/pending",
    APPROVE_SHOP: "/admin/shops/:id/status",
    PRODUCT_APPROVED: "/admin/products/:id/approve",
    PRODUCT_REJECTED: "/admin/products/:id/reject",
    UPDATE_INFO_SHOP: "/admin/shops/:id",
    GET_ALL_PRODUCTS_PENDING: "/admin/products/pending",
    GET_PRODUCT_BY_ID: "/admin/products/:id",
    DELETE_SHOP: "/admin/shops/:id",
  },
  AUTH: {
    LOGIN: "/auth/login",
    LOGIN_GOOGLE: "/auth/google-login",
    GET_CURRENT_USER_INFO: "/auth/me",
    REGISTER: "/auth/register",
    CHANGE_PASSWORD: "/auth/change-password",
    RESET_PASSWORD: "/auth/reset-password",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_NEW_EMAIL: "/auth/verify-new-email",
    RESEND_VERIFICATION_CODE: "/auth/resend-verification-code",
  },
  PRODUCT: {
    GET_ALL_PRODUCTS: "/products",
    GET_PRODUCT_BY_ID: "/products/:id",
    CREATE_PRODUCT: "/products",
    UPDATE_PRODUCT: "/products/:id",
    DELETE_PRODUCT: "/products/:id",
    SEARCH_PRODUCTS: "/products/search",
    CREATE_PRODUCT_IMAGE: "/product-images/:id",
    DELETE_PRODUCT_IMAGE: "/product-images/image/:id",
    DELETE_PRODUCT_IMAGES: "/product-images/product/:id",
  },
  CATEGORY: {
    GET_ALL_CATEGORIES: "/categories",
    GET_CATEGORY_BY_ID: "/categories/:id",
    CREATE_CATEGORY: "/categories",
    UPDATE_CATEGORY: "/categories/:id",
    DELETE_CATEGORY: "/categories/:id",
  },

  USER: {
    UPDATE_PROFILE: "/user/me",
    GET_USER_INFO: "/user/me",
    GET_USER_BY_ID: "/users/:id",
    GET_ALL_USERS: "/users",
    DELETE_USER: "/users/delete/:id",
  },
  SHOP: {
    CREATE_SHOP: "/shops",
    GET_SHOP_BY_ID: "/shops/:id",
    UPDATE_SHOP: "/shops/me",
    DELETE_SHOP: "/shops/delete/:id",
    GET_CURRENT_SHOP: "/shops/me",
  },
  SHOP_APPLICATION: {
    CREATE_APPLICATION: "/shop-applications",
    GET_APPLICATION_BY_ID: "/shop-applications/:id",
  },
  ADDRESS: {
    GET_ADDRESSES: "/addresses",
    CREATE_ADDRESS: "/addresses",
    UPDATE_ADDRESS: "/addresses/:id",
    DELETE_ADDRESS: "/addresses/:id",
  },
  ORDER: {
    CREATE_ORDER: "/orders",
    GET_ORDERS: "/orders",
    GET_ORDER_BY_ID: "/orders/:id",
    UPDATE_ORDER_STATUS: "/orders/:id/status",
    CANCEL_ORDER: "/orders/:id/cancel",
  },
  CART: {
    GET_CART: "/cart",
    ADD_TO_CART: "/cart/add",
    UPDATE_CART: "/cart/update",
    DELETE_CART: "/cart/remove/:id",
    CLEAR_ALL_CART: "/cart/clear",
    CHECK_OUT_CART: "/cart/checkout",
  },
  VOUCHER: {
    GET_VOUCHER: "/vouchers",
    ADD_VOUCHER: "/vouchers",
    UPDATE_VOUCHER: "/vouchers/:id",
    GET_VOUCHER_BY_ID: "/vouchers/:id",
    DELETE_VOUCHER: "/vouchers/:id",
  },
  PAYMENT: {
    MOCK: "/payments/mock",
    ONLINE: "/payments/online",
    MOMO_CREATE: "/payments/momo-create",
    MOMO_RETURN: "/payments/momo-return",
    MOMO_NOTIFY: "/payments/momo-notify",
  },
  REVIEW: {
    CREATE_REVIEW: "/reviews",
    GET_REVIEWS_BY_PRODUCT_ID: "/reviews/:productId",
  },
};
